version: '3'

services:
  rest-marvel:
    build:
      context: ./rest-marvel
    image: rest-marvel
    container_name: rest-marvel
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
    ports:
      - "8080:3000"
    volumes:
      - ./rest-marvel:/home/node/app
      - rest_node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait_for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
    
  cli-marvel-sync:
    build:
      context: ./cli-marvel-sync
    image: cli-marvel-sync
    container_name: cli-marvel-sync
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
      - MARVEL_API_CHARACTERS_ENDPOINT=$MARVEL_API_CHARACTERS_ENDPOINT
      - MARVEL_API_PRIVATE_KEY=$MARVEL_API_PRIVATE_KEY
      - MARVEL_API_PUBLIC_KEY=$MARVEL_API_PUBLIC_KEY
    volumes:
      - ./cli-marvel-sync:/home/node/app
      - cli_node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on: 
      - db
    
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:  
      - dbdata:/data/db   
    networks:
      - app-network  
      
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  rest_node_modules:
  cli_node_modules: